spring:
  redis:
    remote: false        #cachecloud 获取
    host: 10.165.196.97
    port: 6380
    password: N3ighhyp
    pool:
       max-active : 1024
       max-wait : 1000
       max-idle : 100
       min-idle : 50   
  rabbitmq:
    host: 10.165.196.104
    port: 5672
    username: omp
    password: '!QAZ@WSX'
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true
    clients: study-service
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000